name: Generate Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          user: ibtehajhaide669
          template: classic
          theme: github_dark
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
